apiVersion: batch/v1
kind: Job
metadata:
  name: ufo-migrations
  namespace: ufo-ns
spec:
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 100
  backoffLimit: 15

  template:
    spec:
      containers:
      - name: ufo-migrations-container
        image: fak3/ufo:0.5
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "pgwait && ./manage.py migrate --skip-checks"]

        envFrom:
          - configMapRef:
              name: ufo-config
          - secretRef:
              name: postgres-secrets
          - secretRef:
              name: ufo-secrets


      # restartPolicy: Never
      restartPolicy: OnFailure
