apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ufo-ns
  name: ufo-config
  labels:
    app: ufo-config
data:
  DJANGO_SETTINGS_MODULE: settings
  DJANGO_DEBUG : "True"
  DOMAIN_NAME : "*"  # ALLOWED_HOSTS
  ADMIN_EMAIL: "someuniquename@gmail.com"
  GOOGLE_OAUTH2_CLIENT_ID: testid
  UFO_LOGLEVEL: DEBUG

  # Create secrets:
  # read -p "GOOGLE_OAUTH2_CLIENT_SECRET: " google_secret && kubectl create secret generic ufo-secrets --namespace "ufo-ns" --from-literal DJANGO_SECRET_KEY=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1` --from-literal GOOGLE_OAUTH2_CLIENT_SECRET="$google_secret"

