apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufo-deployment
  namespace: ufo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ufo-app
  template:
    metadata:
      labels:
        app: ufo-app
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ufo-app
        image: fak3/ufo:0.4
        ports:
        - containerPort: 8000
          hostPort: 8000
        envFrom:
          - configMapRef:
              name: ufo-config
          - secretRef:
              name: postgres-secrets
          - secretRef:
              name: ufo-secrets
