apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs:
  - /metrics
  - /metrics/slis
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-role
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: ufo-ns
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: ufo-prometheus
spec:
  serviceAccountName: prometheus-sa

  serviceMonitorNamespaceSelector: {}  # auto discover accross all namespaces
  #   matchLabels:
  #     name: ufo
  serviceMonitorSelector: {}  # auto discover all service monitors
  #   matchLabels:
  #     env: staging

  podMonitorNamespaceSelector: {}   # auto discover accross all namespaces
  podMonitorSelector: {}  # auto discover all pod monitors

  ruleNamespaceSelector: {}  # auto discover accross all namespaces
  ruleSelector: {}  # auto discover all rules

  # Prometheus config-reloader has only 10m cpu by default and being constantly throttled,
  # which causes prometheus alert:
  # https://github.com/prometheus-operator/prometheus-operator/issues/5446#issuecomment-1596664300
  # The cpu limit must be changed to at least 30m.
  #
  # The limits set in this Promethus manifest don't affect config-reloader container
  # limits inside the prometheus-operated pod. Instead, it must be set in the
  # prometheus-operator deployment:
  #
  # > kubectl apply -f kube/metrics/prom-operator-deployment.yml
  #
  # See https://github.com/prometheus-operator/kube-prometheus/issues/2333

  resources:
    limits:
      cpu: 300m
      memory: 600Mi
    requests:
      memory: 300Mi
      cpu: 40m

  enableAdminAPI: true
