apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ufo-prometheus-servicemonitor
  # labels:
  #   release: kube-prometheus-stack
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app: ufo-app
      # ufo-prometheus-discovery: 'true'
