apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: ufo-ns
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: someuniquename@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: ufo-gateway
                namespace: ufo-ns
                kind: Gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-cert
  namespace: ufo-ns
spec:
  dnsNames:
    - vybory.live
  issuerRef:
    name: letsencrypt-prod

  # This secret must be referenced by Gateway ufo-gateway to
  # be deployed in production
  secretName: lets-cert-secret

