# Generated by Django 3.0.5 on 2020-05-17 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0004_auto_20200517_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
