# Generated by Django 3.0.5 on 2020-05-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0006_auto_20200520_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orgbranch',
            unique_together={('organization', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='orgjoinapplication',
            unique_together={('organization', 'user')},
        ),
    ]
