# Generated by Django 4.2.15 on 2024-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0007_auto_20200520_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienterror',
            name='data',
            field=models.JSONField(verbose_name='Полученный JSON'),
        ),
        migrations.AlterField(
            model_name='orgbranch',
            name='uik_ranges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='elect_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='incident_conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='limiting_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='unread_notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
