# Generated by Django 5.1.1 on 2024-09-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0012_country_remove_websiteuser_country_region_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ufo.country'),
        ),
    ]
