# Generated by Django 5.1.1 on 2024-09-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0014_alter_region_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default='ru', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='ufo.country'),
            preserve_default=False,
        ),
    ]
