# Generated by Django 5.1.1 on 2024-10-15 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0015_alter_region_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ufo.region'),
        ),
    ]
