# Generated by Django 5.1.1 on 2024-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0017_websiteuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='theme',
            field=models.CharField(default='dark', max_length=30, verbose_name='theme'),
        ),
    ]
