# Generated by Django 3.0.5 on 2020-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0005_auto_20200517_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmembership',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('moderator', 'Модератор'), ('admin', 'Администратор'), ('invited', 'Приглашен')], default='operator', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='orgmembership',
            unique_together={('organization', 'user')},
        ),
    ]
