# Generated by Django 5.1.1 on 2024-09-20 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0008_alter_clienterror_data_alter_orgbranch_uik_ranges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='utc_offset',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-23), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
