# Generated by Django 5.1.1 on 2024-09-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0010_answer_ufo_answer_appuser_or_operator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='ufo_Answer_appuser_or_operator',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('appuser__isnull', True), ('operator__isnull', False)), models.Q(('appuser__isnull', False), ('operator__isnull', True)), _connector='OR'), name='ufo_Answer_appuser_or_operator', violation_error_code='ufo.Answer.creator_not_null', violation_error_message='Ответ должен иметь создателя - оператора или пользователя приложения'),
        ),
    ]
