# Generated by Django 5.1.1 on 2024-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0016_alter_answer_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='theme',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='theme'),
        ),
    ]
