# Generated by Django 5.1.1 on 2024-10-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0018_alter_websiteuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='language',
            field=models.CharField(default='en', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='theme',
            field=models.CharField(default='dark', max_length=30, verbose_name='Theme'),
        ),
    ]
