# Generated by Django 5.1.1 on 2024-11-08 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0019_websiteuser_language_alter_websiteuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(3, 'Name must contain at least 3 characters')]),
        ),
    ]
