# Generated by Django 5.1.1 on 2024-11-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0020_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Photo'),
        ),
    ]
