# Generated by Django 5.1.5 on 2025-02-02 07:17

import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import types
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0023_alter_tik_uik_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='ufo.country'),
        ),
        migrations.AlterField(
            model_name='tik',
            name='uik_ranges',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of ranges.', null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(list, (int,)),)), types.NoneType)), verbose_name='Subordinate UIK ranges'),
        ),
    ]
