# Generated by Django 5.1.5 on 2025-02-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0024_alter_election_country_alter_tik_uik_ranges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='campaign',
        ),
    ]
