# Generated by Django 5.1.5 on 2025-02-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0025_remove_contact_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztopic',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiztopics', to='ufo.country'),
        ),
    ]
