# Generated by Django 5.1.5 on 2025-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0027_websiteuser_num_login_emails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
