# Generated by Django 5.1.5 on 2025-03-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0029_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='00410ede-fee6-450f-82df-186fc4663d19', on_delete=django.db.models.deletion.CASCADE, to='ufo.question'),
            preserve_default=False,
        ),
    ]
