name: Test & Deploy Preview

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.toml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests_job:
    env:
      DATABASE_URL: "sqlite://:memory:"
      DJANGO_SECRET_KEY: test
      ADMIN_EMAIL: "someuniquename@gmail.com"
      GOOGLE_OAUTH2_CLIENT_ID: test
      GOOGLE_OAUTH2_CLIENT_SECRET: test
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      # - name: install dependencies
      #   run: |
      #       sudo apt-get -y install chromium libasound2t64

      - name: Setup Python Versions
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.12

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          allow-prereleases: true

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}

      - name: Install PDM via pip
        run: python -m pip install pdm

      - name: Install Dev Dependencies
        run: |
          pdm install -v --group test --group uitest
          pdm run pip install -U setuptools
          pdm info

      - name: install playwright dependencies
        run: |
            pdm run playwright install chromium

      - name: collect static files
        run: |
            pdm run ./manage.py collectstatic --no-input

      - name: Run Tests
        run: pdm run pytest --doctest-modules -s -vv

      # - name: Upload results to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.xml

  deploy_preview_job:
    needs: tests_job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Deploy preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          # vercel-args: '--prod' #Optional
          vercel-args: '--yes'
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          vercel-version: 39.2.5

