name: test-main

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.toml"

concurrency:
  # only one at a time is allowed
  group: production
  cancel-in-progress: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests_job:
    uses: ./.github/workflows/tests.yml

  deploy_preview_job:
    needs: tests_job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Deploy preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--yes'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-version: 39.2.5

  ping_preview_job:
    needs: deploy_preview_job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: curl
        run: curl https://elect-hotline-fak3-roman-s-projects-e5269d8.vercel.app/

