name: Tests

on:
  workflow_call:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests_job:
    env:
      DATABASE_URL: "sqlite://:memory:"
      DJANGO_SECRET_KEY: test
      ADMIN_EMAIL: "someuniquename@gmail.com"
      GOOGLE_OAUTH2_CLIENT_ID: test
      GOOGLE_OAUTH2_CLIENT_SECRET: test

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      # - name: install dependencies
      #   run: |
      #       sudo apt-get -y install chromium libasound2t64

      - name: Setup Python Versions
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.12

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          allow-prereleases: true

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}

      - name: Install PDM via pip
        run: python -m pip install pdm

      - name: Install Dev Dependencies
        run: |
          pdm install -v --group test --group uitest
          pdm run pip install -U setuptools
          pdm info

      - name: install playwright dependencies
        run: |
            pdm run playwright install chromium

      - name: collect static files
        run: |
            pdm run ./manage.py collectstatic --no-input

      - name: Run Tests
        run: pdm run pytest --doctest-modules -s -vv --cov --cov-config=pyproject.toml --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
